import React from "react";
import Nav from 'react-bootstrap/Nav';
import Sidebar from './sidebar'
import './../styles/dashboard.css';


class Dashboard extends React.Component {
  render() {
    return (
      <div className="row dashboard">
        
        <Sidebar />
        <div class="col-2 invisible"> {/*hidden spacer*/}</div>
        <div className="col-10 content">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet purus gravida quis blandit turpis cursus in. Ut porttitor leo a diam sollicitudin tempor id. Velit dignissim sodales ut eu. In ornare quam viverra orci sagittis eu volutpat. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Sit amet facilisis magna etiam. Adipiscing at in tellus integer feugiat scelerisque varius morbi enim. Sed odio morbi quis commodo odio aenean. Amet consectetur adipiscing elit duis tristique sollicitudin. Congue quisque egestas diam in arcu. Dolor morbi non arcu risus. Interdum consectetur libero id faucibus. Cursus metus aliquam eleifend mi. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Feugiat pretium nibh ipsum consequat nisl. Dignissim sodales ut eu sem integer vitae justo. Duis tristique sollicitudin nibh sit amet.

Amet consectetur adipiscing elit pellentesque habitant morbi. Elementum eu facilisis sed odio morbi. Diam ut venenatis tellus in. Commodo viverra maecenas accumsan lacus. Luctus venenatis lectus magna fringilla. At urna condimentum mattis pellentesque id nibh tortor. Tristique risus nec feugiat in fermentum posuere urna. Viverra nam libero justo laoreet. Purus ut faucibus pulvinar elementum integer enim. Nulla at volutpat diam ut. Tellus integer feugiat scelerisque varius morbi enim nunc. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Odio morbi quis commodo odio. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Sit amet massa vitae tortor condimentum lacinia quis. Purus viverra accumsan in nisl nisi scelerisque. In nibh mauris cursus mattis molestie a iaculis at erat.

Magna ac placerat vestibulum lectus mauris. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. A lacus vestibulum sed arcu non. Eget nunc lobortis mattis aliquam faucibus purus in. Tempus urna et pharetra pharetra massa massa. Leo in vitae turpis massa sed elementum tempus egestas sed. Vitae suscipit tellus mauris a. Sed enim ut sem viverra aliquet eget sit amet. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Massa eget egestas purus viverra accumsan in. Vitae tempus quam pellentesque nec nam aliquam. Lacus laoreet non curabitur gravida arcu ac. Amet cursus sit amet dictum. Purus in massa tempor nec feugiat nisl.

Mi proin sed libero enim. Tempus egestas sed sed risus pretium quam vulputate. Convallis tellus id interdum velit laoreet id. Suscipit tellus mauris a diam maecenas sed. Natoque penatibus et magnis dis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Consectetur a erat nam at lectus urna. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Volutpat est velit egestas dui id ornare arcu odio ut. Auctor urna nunc id cursus metus aliquam eleifend. Scelerisque eleifend donec pretium vulputate sapien. Etiam non quam lacus suspendisse faucibus. Amet nisl purus in mollis nunc sed id semper risus. Mattis rhoncus urna neque viverra justo nec ultrices. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec.

Neque laoreet suspendisse interdum consectetur. Neque viverra justo nec ultrices dui sapien eget. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Pharetra diam sit amet nisl. Sem nulla pharetra diam sit amet. Et ultrices neque ornare aenean euismod. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Molestie ac feugiat sed lectus. Sit amet aliquam id diam maecenas ultricies mi. Diam quam nulla porttitor massa id neque aliquam. Egestas dui id ornare arcu odio ut sem nulla. Lectus sit amet est placerat in egestas. Praesent tristique magna sit amet purus gravida quis blandit. Accumsan lacus vel facilisis volutpat est velit egestas. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Varius morbi enim nunc faucibus a pellentesque sit amet. Sed felis eget velit aliquet sagittis id consectetur purus ut. Aliquet risus feugiat in ante metus dictum at.

Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Augue eget arcu dictum varius duis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Tellus orci ac auctor augue mauris augue neque gravida. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Turpis nunc eget lorem dolor sed viverra ipsum. Placerat duis ultricies lacus sed turpis tincidunt. Convallis convallis tellus id interdum velit laoreet id donec. Sem integer vitae justo eget magna fermentum. Est ante in nibh mauris cursus. Ultrices neque ornare aenean euismod elementum nisi. Faucibus interdum posuere lorem ipsum dolor sit. Faucibus purus in massa tempor nec feugiat. Purus gravida quis blandit turpis cursus in hac habitasse platea. Iaculis eu non diam phasellus vestibulum lorem sed risus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Scelerisque viverra mauris in aliquam. Porttitor eget dolor morbi non arcu. Nulla porttitor massa id neque aliquam.

Suspendisse interdum consectetur libero id faucibus. Ultrices neque ornare aenean euismod. Mauris commodo quis imperdiet massa. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Est lorem ipsum dolor sit amet consectetur adipiscing. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Ac felis donec et odio pellentesque diam volutpat. Dui accumsan sit amet nulla facilisi. Aenean et tortor at risus viverra adipiscing at. Suspendisse in est ante in. Morbi blandit cursus risus at ultrices mi tempus. Adipiscing vitae proin sagittis nisl. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Aliquet nibh praesent tristique magna. Quis eleifend quam adipiscing vitae proin. Non blandit massa enim nec dui nunc mattis. Est ultricies integer quis auctor.

Et malesuada fames ac turpis egestas. Sollicitudin aliquam ultrices sagittis orci. Mauris nunc congue nisi vitae suscipit tellus mauris. Convallis tellus id interdum velit laoreet id donec ultrices. In tellus integer feugiat scelerisque varius morbi. Urna nunc id cursus metus. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Elit pellentesque habitant morbi tristique. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Tortor vitae purus faucibus ornare suspendisse sed. Neque viverra justo nec ultrices dui sapien. Facilisis mauris sit amet massa vitae tortor condimentum. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan.

Sit amet luctus venenatis lectus magna fringilla. Metus dictum at tempor commodo ullamcorper a lacus. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Fringilla phasellus faucibus scelerisque eleifend. Convallis aenean et tortor at risus viverra adipiscing at. Sit amet aliquam id diam maecenas ultricies mi eget. Odio ut enim blandit volutpat maecenas volutpat. Mi ipsum faucibus vitae aliquet. Sit amet cursus sit amet dictum. Duis at consectetur lorem donec massa.

Nisi vitae suscipit tellus mauris. Ac odio tempor orci dapibus ultrices. Nunc lobortis mattis aliquam faucibus purus in. Varius morbi enim nunc faucibus a pellentesque sit amet. Orci sagittis eu volutpat odio facilisis mauris. Vitae tempus quam pellentesque nec nam aliquam sem et. Ac auctor augue mauris augue neque gravida in fermentum et. Adipiscing elit ut aliquam purus sit amet luctus. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Elementum nibh tellus molestie nunc non blandit. Nec ullamcorper sit amet risus nullam eget felis eget. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Id volutpat lacus laoreet non curabitur gravida. Massa massa ultricies mi quis hendrerit dolor magna. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque.
        </div>
      </div>
		);
	}
}

export default Dashboard